# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  fly-deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  publish-nuget:
    runs-on: ubuntu-latest
    needs: fly-deploy
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build Contracts Library
        run: dotnet build SimpleService.Contracts/SimpleService.Contracts.csproj -c Release

      - name: Set version from Git tag
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "1.0.${{ github.run_number }}")
          echo "Version: $VERSION"
          sed -i "s|<Version>.*</Version>|<Version>$VERSION</Version>|g" SimpleService.Contracts/SimpleService.Contracts.csproj
        continue-on-error: true

      - name: Build and Pack NuGet package
        run: dotnet pack SimpleService.Contracts/SimpleService.Contracts.csproj -c Release -o out

      - name: Publish NuGet package
        run: dotnet nuget push out/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

  publish-to-npm:
    runs-on: ubuntu-latest
    needs: fly-deploy

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restaurar dependencias
        run: dotnet restore SimpleService.Application/SimpleService.Application.csproj

      - name: Construir aplicación
        run: dotnet build SimpleService.Application/SimpleService.Application.csproj -c Release

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"

      - name: Instalar dependencias
        run: npm install
        working-directory: SimpleService.Application/generated-ts-types

      - name: Construir paquete TypeScript
        run: npm run build
        working-directory: SimpleService.Application/generated-ts-types

      - name: Publicar en npm
        run: npm publish --access public
        working-directory: SimpleService.Application/generated-ts-types
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}