name: CI/CD - Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build de la imagen Docker
        run: docker build -t alipacala/simpleservice:latest .

      - name: Login en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "alipacala" --password-stdin

      - name: Publicar en Docker Hub
        run: docker push alipacala/simpleservice:latest
