name: CI/CD - Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build de la imagen Docker
        run: docker build -t miusuario/miimagen:latest .

      - name: Publicar en Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "miusuario" --password-stdin
          docker push miusuario/miimagen:latest

  restart-app-service:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Login en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Reiniciar Azure App Service (Opcional)
        run: az webapp restart --name MiAppService --resource-group MiResourceGroup
